### ISSUE TITLE
Use of uninitialized value 

### ISSUE THREAD

**Issue by xpunkt** [msimerson/mail-dmarc#112]
[001] dmarc forensic report for example.org from ip xxx.xxx,xxx.xxx
Use of uninitialized value in split at /usr/lib64/perl5/vendor_perl/5.24.1/Mail/DMARC/Report/Receive.pm line 140.
Use of uninitialized value $c_type in string eq at /usr/lib64/perl5/vendor_perl/5.24.1/Mail/DMARC/Report/Receive.pm line 141.
Use of uninitialized value $c_type in string eq at /usr/lib64/perl5/vendor_perl/5.24.1/Mail/DMARC/Report/Receive.pm line 142.
Use of uninitialized value $c_type in string eq at /usr/lib64/perl5/vendor_perl/5.24.1/Mail/DMARC/Report/Receive.pm line 147.
Use of uninitialized value $c_type in string eq at /usr/lib64/perl5/vendor_perl/5.24.1/Mail/DMARC/Report/Receive.pm line 153.
Use of uninitialized value $c_type in string eq at /usr/lib64/perl5/vendor_perl/5.24.1/Mail/DMARC/Report/Receive.pm line 153.
Use of uninitialized value $c_type in string eq at /usr/lib64/perl5/vendor_perl/5.24.1/Mail/DMARC/Report/Receive.pm line 162.
Use of uninitialized value $c_type in concatenation (.) or string at /usr/lib64/perl5/vendor_perl/5.24.1/Mail/DMARC/Report/Receive.pm line 169.
Unknown message part

**Comment by xpunkt** [comment]
http://gentoo-overlays.zugaina.org/fidonet/dev-perl.html.en#Mail-DMARC

is what i use on gentoo, more info needed ?

**Comment by msimerson** [comment]
This error was emitted because the forensic report / email message apparently didn't contain any MIME parts, or Email::MIME was unable to parse it. Either way, there's nothing we can do without a full copy of that raw email.

**Comment by xpunkt** [comment]
[DMARC Forensic Report for junc.eu from IP 95.128.36.21.txt](https://github.com/msimerson/mail-dmarc/files/1243654/DMARC.Forensic.Report.for.junc.eu.from.IP.95.128.36.21.txt)

**Comment by msimerson** [comment]
Well, that explains it. There are no MIME parts in that message. No MIME parts means no content types. Years ago, when I last looked at forensic reports, the actual reports were anything but standardized. The example provided in [RFC 6591](https://www.rfc-editor.org/rfc/rfc6591.txt) was at least MIME encoded. My experience with receiving forensic reports was that the formats were anything but standard. Because their format isn't consistent, I've always had them sent to another email address  and thus Mail::DMARC doesn't really have support for them.

If you wish to amend Mail::DMARC to do something more with messages w/o MIME types (maybe just emit a spiffy error message?), PRs are welcome.
