### ISSUE TITLE
Parse error in Policy

### ISSUE THREAD

**Issue by marcbradshaw** [msimerson/mail-dmarc#20]
Odd number of elements in anonymous hash at /usr/share/perl5/Mail/DMARC/Policy.pm line 31.

No context as yet, putting this here as a reminder to investigate.

**Comment by msimerson** [comment]
It's barking about this line:

```perl
my $policy = { map { split /=/, $_ } split /;/, $str };
```

Which means that Mail::DMARC retrieved a DMARC record that wasn't valid. Example DMARC record:
````
"v=DMARC1\; p=reject\; rua=mailto:dmarc-feedback@theartfarm.com\; ruf=mailto:dmarc-feedback@theartfarm.com\; pct=100"
````
The cleanups in the previous lines (28-30) turn that into this string:
````
v=DMARC1;p=reject;rua=mailto:dmarc-feedback@theartfarm.com;ruf=mailto:dmarc-feedback@theartfarm.com;pct=100"
````

Then the first split on `;` breaks it into this array of strings:
```perl
(
    v=DMARC1
    p=reject
    rua=mailto:dmarc-feedback@theartfarm.com
    ruf=mailto:dmarc-feedback@theartfarm.com
    pct=100
)
```
and that array gets passed to map which splits on the `=` character, resulting in this hash:
```perl
{
    v => DMARC1
    p => reject
    rua => mailto:dmarc-feedback@theartfarm.com
    ruf => mailto:dmarc-feedback@theartfarm.com
    pct => 100
}
```

That error you are getting is telling you that you ended up getting a DMARC record that looked like this:

````
v=DMARC1;p=reject;rua=mailto:dmarc-feedback@theartfarm.com;ruf=mailto:dmarc-feedback@theartfarm.com;pct=
````
Note the missing value after the pct=. 

The [formal spec](http://tools.ietf.org/html/draft-kucherawy-dmarc-base-12#section-6.4) provides an ABNF and while this parser is a bit naive, it should reliably parse any valid DMARC record. Whether you want to try massaging the results of an invalid record into something worth acting on seems a path towards pain and suffering to me.

I wonder if you didn't receive a truncated DNS record.

**Comment by marcbradshaw** [comment]
Don't think it's worth trying to massage the bad records, too many assumptions need to be made on how they are broken.
Would rather it didn't throw a warning, would be better to return a fail result with an invalid record reason perhaps?

**Comment by msimerson** [comment]
I'm conflicted on this. 

```perl
my $policy = { map { split /=/, $_ } split /;/, $str };
croak "invalid policy" if !$self->is_valid($policy);
```
The warning is being generated in the first line. We **could** put some validation in there by parsing into separate steps and then testing that the `split /=/` produces @elements % 2 = 0. That way you could also suppress the warning. However, rejecting there would also mean that a DMARC record that would otherwise have passed validation in the 2nd line will get rejected.

If DMARC did not have reporting capabilities in which we report back to the author domain the DMARC policy that we applied, I'd be more inclined to reject those partial records. But DMARC does have reporting, and an author domain wondering why a message was treated differently than their stated DNS policy will now have evidence that receivers are handling their DMARC policy differently than they asked (say perhaps because their p= or pct= was at the end of a truncated DNS record) and are thus able to investigate further and fix their DNS configuration.

Either way, on our end I think issuing a warning when something like that happens is the right thing to do.

**Comment by msimerson** [comment]
In a case like this, I want to see the warnings and you don't. It wouldn't be much fun for you to maintain a branch/patch/whatever that adds a 'no warnings' line, or comments out the use warnings for the entire file. 

One possible solution is to have a config toggle to enable/disable warnings.

**Comment by marcbradshaw** [comment]
It's not that I don't want to see warnings, they area useful thing, but in this case I am getting the warning out of context. Warnings are going to a separate log file and cannot be easily correlated with the original request.

One possible issue with the current code is if a policy is published such as

v=DMARC1;p=reject;rua=mailto:dmarc-feedback@theartfarm.com;pct=;ruf=mailto:dmarc-feedback@theartfarm.com

with the "pct=" before another tuple, then the resulting hashref has values for keys in places.

We could force the split to return 2 elements regardless of contents, would protect against malformed records with multiple '=' in an entry too.


Something like this perhaps?

my $mysplit = sub {
    my $line = shift;
    my @split = split /=/, $line, 2;
    if ( scalar @split == 1 ) { 
        push @split, undef;
    }   
    return @split;
};

my $policy = { map { &$mysplit( $_ ) } split /;/, $str };

**Comment by msimerson** [comment]
#39 reports the DNS record that failed validation. @marcbradshaw points out that it would be helpful to also report the domain where the DNS record was found.
