### ISSUE TITLE
Invalid DKIM results cause SQL error

### ISSUE THREAD

**Issue by marcbradshaw** [msimerson/mail-dmarc#21]
When DKIM returns an invalid result, for example "invalid (public key: DNS error: query timed out)" and is then passed to DMARC an error inserting into the database is generated.

This also happens if a message has multiple signatures and one or more of them is invalid.

Should we be inserting the invalid record, or simply ignoring it?

query called by Mail::DMARC::Report::Store::SQL, 527#012#011INSERT INTO report_record_dkim#012    (report_record_id, domain_id,selector,result,human_result)#012VALUES (??)#012#012#0111376426, 113974, dkim, invalid, invalid (public key: DNS error: query timed out) at /usr/share/perl5/Mail/DMARC/Report.pm line 77

**Comment by msimerson** [comment]
Hmmm. I'm thinking a little bit more code belongs in Mail::DMARC::dkim_from_mail_dkim. In a case like this one (DNS timeout), the result `invalid` should be mapped to `temperror` and then the insert wouldn't fail (due to violating the foreign key constraint). We can probably just map any `invalid` result to `temperror` until proven otherwise. At least that way, the "why" makes it into the database and perhaps reported back to the domain with the issue. 

What do you think?

**Comment by marcbradshaw** [comment]
Sounds reasonable to me.

**Comment by msimerson** [comment]
@marcbradshaw, I think this change will do it for you. Please test and confirm, and if not, reopen this Issue.

**Comment by marcbradshaw** [comment]
Looks fine, I'll let it run for a while and reopen if there are more errors.
