### ISSUE TITLE
result->reason is an arrayref of objects, not hashrefs

### ISSUE THREAD

**Issue by rjbs** [msimerson/mail-dmarc#32]
The docs for Result indicate that `->reason` will return hashrefs, but actually it's objects.

I was pretty confused by the whole `->reason` method, actually.  Its name is singular, but it returns potentially many things.  It returns an arrayref, which makes me worry a bit about mutation, but that's less of a big deal.  When there is no reason, it returns `undef` instead of `[]`.

I didn't propose a documentation patch because I wonder whether the whole way that one can inspect a Result to determine what really happened can't be generally improved overall.  If nothing else, though, this ticket represents the one definite way in which docs disagree with reality. :-)

**Comment by msimerson** [comment]
Here's why it was named `reason` (from [the IEFT Draft](http://tools.ietf.org/html/draft-kucherawy-dmarc-base-12)):
```xml
   <xs:complexType name="PolicyOverrideReason">
     <xs:all>
       <xs:element name="type" type="PolicyOverrideType"/>
       <xs:element name="comment" type="xs:string" minOccurs="0"/>
     </xs:all>
   </xs:complexType>

<!-- Taking into account everything else in the record, the results of applying DMARC. -->
   <xs:complexType name="PolicyEvaluatedType">
     <xs:sequence>
       <xs:element name="disposition" type="DispositionType"/>
       <xs:element name="dkim" type="DMARCResultType"/>
       <xs:element name="spf" type="DMARCResultType"/>
       <xs:element name="reason" type="PolicyOverrideReason" minOccurs="0" maxOccurs="unbounded"/>
     </xs:sequence>
   </xs:complexType>
```
You may notice that most of the method names have a one-to-one correlation with the data they represent. Absent a compelling reason otherwise, I think that's a convention worth maintaining.

> I wonder whether the whole way that one can inspect a Result to determine what really happened can't be generally improved overall

I'm open to suggestions, and PRs are even better.

**Comment by rjbs** [comment]
I'll keep thinking.

I think the XML Schema isn't necessarily an idea source of naming.  After all, it's saying that this is legal:

```xml
<reason>...</reason>
<reason>...</reason>
<reason>...</reason>
```

That is, you can have many `reason` elements.  Each one is an item.  The attribute on the Result object, though, represents a collection.

**Comment by SebastianS90** [comment]
I think there is a bug with handling the reasons in Mail/DMARC/Report/Store/SQL.pm insert_agg_record.

My code to overwrite the policy and set a reason is:
```perl
my $policy = $dmarc->discover_policy;
my $result = $dmarc->validate($policy);
$result->disposition('none');
$result->reason(type => 'local_policy');
$dmarc->save_aggregate();
```

It correctly stores 'none' instead of 'reject' to the database, but there is no entry in the report_record_reason table.


The insert_agg_record method looks like:
```perl
    my $reasons = $rec->{row}{policy_evaluated}{reason};
    if ( $reasons ) {
        foreach my $reason ( @$reasons ) {
            next if !$reason || !$reason->{type};
            $self->insert_rr_reason( $row_id, $reason->{type}, $reason->{comment} );
        };
    }
```

If I do print Dumper $reasons in this method, I get:
```perl
$VAR1 = [ 
          [ 
            bless( { 
                     'type' => 'local_policy'
                   }, 'Mail::DMARC::Result::Reason' )
          ]
        ];
````

I don't really know perl, but for me it looks like a array of arrays and the next-command skips the reason.
