### ISSUE TITLE
evals without error handling lose data

### ISSUE THREAD

**Issue by rjbs** [msimerson/mail-dmarc#68]
Mail::DMARC::PurePerl has the following code:

```perl
eval { $self->is_dkim_aligned; };
eval { $self->is_spf_aligned;  };
```

...which is good, because it prevents an error checking SPF from crashing the whole program.  On the other hand, it simply drops any error on the floor, which can make diagnosing problems a bit confusing.  (Especially so because both SPF and DKIM can come from user-provided callbacks.)

I have locally written those as "eval { ...; 1 } or warn $@" for now, but maybe you've got some other means by which you think this could or should be done (error callback?).

**Comment by msimerson** [comment]
Any error that gets caught there is meaningless to me. You're welcome to made your mod there if it helps you out.

**Comment by msimerson** [comment]
Since I'm not inclined to do anything about this, and @rjbs hasn't yet cared enough to, I'm inclined to close this. Objections?

**Comment by rjbs** [comment]
It's up to you.  If you leave it open, I may get to it eventually.  If you don't, I still might, but am more likely to forget.  If you don't really care, and only find the open issue to be a distraction, I will not be put out if you close it.

**Comment by msimerson** [comment]
I like the issue tracker to be clean and tidy. I'll add this to a Maybe TODO on the wiki with a link here.

**Comment by jb-wisemo** [comment]
Implementation note for this TODO: Failure should probably be mapped to the appropriate mechanism specific "technical failure" result code ("Temperror" for SPF, "TEMPFAIL" for DKIM).

Using the corresponding "permanent failure" codes would only be correct if retrying the check later in a new process context would be certain to fail in the same way, however only the SPF/DKIM checking code could reliably make such a determination, in which case it should simply return the "permanent failure" code itself rather than crashing.
