### ISSUE TITLE
Update of public_suffix_list

### ISSUE THREAD

**Issue by abeverley** [msimerson/mail-dmarc#84]
Would it be possible to update the default public_suffix_list in the distribution please? I realise I can update this myself, but it would be useful to know that I don't have to remember to do so next time I install the module ;-)

Thanks for a great module,

Andy

**Comment by msimerson** [comment]
Yes, it's quite possible to update in the distribution. I have several thoughts that I'd happily accept PRs for (I'm on holiday now and will be quite busy for a while after returning):

1. Add a section to DEVELOP.md with things to do before cutting a release. On such item on the list would be: update PSL.

2. Remove the PSL from the distro entirely, since we already added code that loads and keeps the PSL updated. Make sure docs are up-to-date.

**Comment by rjbs** [comment]
I think I'd probably lean toward (2) because otherwise the PSL is only as recent as the dist.  When the dist's frequency of release goes down, the shipped PSL is more and more out of date.

That said, I would be happy to write a Dist::Zilla plugin to check that the PSL is up to date or something, if you prefer to go that way.

**Comment by msimerson** [comment]
I lean towards #2 as well. Automatically keeping the PSL up to date at run time seems the most reasonable default. We just need to make sure that our update code creates the sharedir if missing (due to removal of PSL from the dist.)

**Comment by rjbs** [comment]
That should be no problem.  We just throw a zero-byte file in ./share and call it a day. ;)

**Comment by msimerson** [comment]
I haven't looked into it far enough, but our auto-update solution for the PSL isn't as robust enough to skip including it in the distro:

````
% sudo /usr/local/bin/dmarc_update_public_suffix_list
HTTP Request for Public Suffix List file failed with error 599 (Could not connect to 'publicsuffix.org:443': Non-recoverable failure in name resolution
)
% fetch https://publicsuffix.org/list/effective_tld_names.dat
effective_tld_names.dat                       100% of  172 kB  583 kBps 00m00s
% sudo mv effective_tld_names.dat /usr/local/lib/perl5/site_perl/auto/share/dist/Mail-DMARC/public_suffix_list
````
